"""baseline_schema

Revision ID: 3f35fadc1e13
Revises: 
Create Date: 2026-09-10 16:06:44.315528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f35fadc1e13'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())

    if 'agent_action_audits' not in existing_tables:
        op.create_table('agent_action_audits',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('action_id', sa.String(length=50), nullable=True),
        sa.Column('user_id', sa.String(length=50), nullable=True),
        sa.Column('intent', sa.String(length=100), nullable=False),
        sa.Column('tool_name', sa.String(length=100), nullable=False),
        sa.Column('parameters', sa.Text(), nullable=True),
        sa.Column('result', sa.Text(), nullable=True),
        sa.Column('requires_confirmation', sa.Boolean(), nullable=True),
        sa.Column('confirmed', sa.Boolean(), nullable=True),
        sa.Column('status', sa.String(length=30), nullable=True),
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_agent_action_audits_action_id'), 'agent_action_audits', ['action_id'], unique=True)
        op.create_index(op.f('ix_agent_action_audits_id'), 'agent_action_audits', ['id'], unique=False)
        op.create_index(op.f('ix_agent_action_audits_tool_name'), 'agent_action_audits', ['tool_name'], unique=False)

    if 'events' not in existing_tables:
        op.create_table('events',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('title', sa.String(length=150), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('event_type', sa.String(length=30), nullable=True),
        sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
        sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
        sa.Column('location', sa.String(length=100), nullable=True),
        sa.Column('meet_url', sa.String(length=255), nullable=True),
        sa.Column('is_mandatory', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
        op.create_index(op.f('ix_events_start_time'), 'events', ['start_time'], unique=False)

    if 'students' not in existing_tables:
        op.create_table('students',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('student_code', sa.String(length=20), nullable=True),
        sa.Column('full_name', sa.String(length=100), nullable=False),
        sa.Column('arabic_name', sa.String(length=100), nullable=False),
        sa.Column('email', sa.String(length=100), nullable=False),
        sa.Column('phone', sa.String(length=30), nullable=False),
        sa.Column('university', sa.String(length=100), nullable=True),
        sa.Column('role', sa.String(length=50), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('team_id', sa.String(length=36), nullable=True),
        sa.Column('assigned_hr_id', sa.String(length=36), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['assigned_hr_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_students_arabic_name'), 'students', ['arabic_name'], unique=False)
        op.create_index(op.f('ix_students_assigned_hr_id'), 'students', ['assigned_hr_id'], unique=False)
        op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
        op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
        op.create_index(op.f('ix_students_student_code'), 'students', ['student_code'], unique=True)
        op.create_index(op.f('ix_students_team_id'), 'students', ['team_id'], unique=False)

    if 'teams' not in existing_tables:
        op.create_table('teams',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('code', sa.String(length=50), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
        )
        op.create_index(op.f('ix_teams_code'), 'teams', ['code'], unique=True)
        op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)

    if 'users' not in existing_tables:
        op.create_table('users',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('email', sa.String(length=100), nullable=False),
        sa.Column('hashed_password', sa.String(length=255), nullable=False),
        sa.Column('full_name', sa.String(length=100), nullable=False),
        sa.Column('arabic_name', sa.String(length=100), nullable=True),
        sa.Column('role', sa.String(length=50), nullable=True),
        sa.Column('team_id', sa.String(length=36), nullable=True),
        sa.Column('student_id', sa.String(length=36), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
        sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
        op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
        op.create_index(op.f('ix_users_student_id'), 'users', ['student_id'], unique=False)
        op.create_index(op.f('ix_users_team_id'), 'users', ['team_id'], unique=False)

    if 'automation_settings' not in existing_tables:
        op.create_table('automation_settings',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('user_id', sa.String(length=36), nullable=False),
        sa.Column('attendance_enabled', sa.Boolean(), nullable=True),
        sa.Column('attendance_grace_minutes', sa.Integer(), nullable=True),
        sa.Column('attendance_message', sa.Text(), nullable=True),
        sa.Column('task_pre_enabled', sa.Boolean(), nullable=True),
        sa.Column('task_pre_hours', sa.Integer(), nullable=True),
        sa.Column('task_pre_message', sa.Text(), nullable=True),
        sa.Column('task_post_enabled', sa.Boolean(), nullable=True),
        sa.Column('task_post_delay_hours', sa.Integer(), nullable=True),
        sa.Column('task_post_message', sa.Text(), nullable=True),
        sa.Column('whatsapp_enabled', sa.Boolean(), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_automation_settings_id'), 'automation_settings', ['id'], unique=False)
        op.create_index(op.f('ix_automation_settings_user_id'), 'automation_settings', ['user_id'], unique=True)

    if 'committee_reports' not in existing_tables:
        op.create_table('committee_reports',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('team_id', sa.String(length=36), nullable=False),
        sa.Column('submitted_by_user_id', sa.String(length=36), nullable=False),
        sa.Column('report_title', sa.String(length=150), nullable=False),
        sa.Column('metrics_summary', sa.Text(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_committee_reports_id'), 'committee_reports', ['id'], unique=False)
        op.create_index(op.f('ix_committee_reports_submitted_by_user_id'), 'committee_reports', ['submitted_by_user_id'], unique=False)
        op.create_index(op.f('ix_committee_reports_team_id'), 'committee_reports', ['team_id'], unique=False)

    if 'meetings' not in existing_tables:
        op.create_table('meetings',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('meeting_code', sa.String(length=50), nullable=True),
        sa.Column('title', sa.String(length=150), nullable=False),
        sa.Column('topic', sa.String(length=200), nullable=True),
        sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
        sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
        sa.Column('duration_minutes', sa.Integer(), nullable=True),
        sa.Column('meet_url', sa.String(length=255), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('session_number', sa.Integer(), nullable=True),
        sa.Column('responsible_user_id', sa.String(length=36), nullable=True),
        sa.Column('team_id', sa.String(length=36), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_meetings_id'), 'meetings', ['id'], unique=False)
        op.create_index(op.f('ix_meetings_meeting_code'), 'meetings', ['meeting_code'], unique=True)
        op.create_index(op.f('ix_meetings_responsible_user_id'), 'meetings', ['responsible_user_id'], unique=False)
        op.create_index(op.f('ix_meetings_team_id'), 'meetings', ['team_id'], unique=False)

    if 'member_feedbacks' not in existing_tables:
        op.create_table('member_feedbacks',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('student_id', sa.String(length=36), nullable=False),
        sa.Column('hr_member_id', sa.String(length=36), nullable=True),
        sa.Column('hr_member_name', sa.String(length=100), nullable=True),
        sa.Column('category', sa.String(length=50), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('reviewed_by_user_id', sa.String(length=36), nullable=True),
        sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['hr_member_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_member_feedbacks_hr_member_id'), 'member_feedbacks', ['hr_member_id'], unique=False)
        op.create_index(op.f('ix_member_feedbacks_id'), 'member_feedbacks', ['id'], unique=False)
        op.create_index(op.f('ix_member_feedbacks_student_id'), 'member_feedbacks', ['student_id'], unique=False)

    if 'member_followup_statuses' not in existing_tables:
        op.create_table('member_followup_statuses',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('student_id', sa.String(length=36), nullable=False),
        sa.Column('hr_member_id', sa.String(length=36), nullable=False),
        sa.Column('flagged_reason', sa.String(length=100), nullable=False),
        sa.Column('flagged_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('status', sa.String(length=30), nullable=True),
        sa.Column('is_escalated', sa.Boolean(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['hr_member_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_member_followup_statuses_hr_member_id'), 'member_followup_statuses', ['hr_member_id'], unique=False)
        op.create_index(op.f('ix_member_followup_statuses_id'), 'member_followup_statuses', ['id'], unique=False)
        op.create_index(op.f('ix_member_followup_statuses_student_id'), 'member_followup_statuses', ['student_id'], unique=False)

    if 'member_questions' not in existing_tables:
        op.create_table('member_questions',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('student_id', sa.String(length=36), nullable=False),
        sa.Column('team_id', sa.String(length=36), nullable=False),
        sa.Column('title', sa.String(length=150), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('asked_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('answered_by_user_id', sa.String(length=36), nullable=True),
        sa.Column('answer', sa.Text(), nullable=True),
        sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['answered_by_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
        sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_member_questions_id'), 'member_questions', ['id'], unique=False)
        op.create_index(op.f('ix_member_questions_student_id'), 'member_questions', ['student_id'], unique=False)
        op.create_index(op.f('ix_member_questions_team_id'), 'member_questions', ['team_id'], unique=False)

    if 'reminder_logs' not in existing_tables:
        op.create_table('reminder_logs',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('recipient_id', sa.String(length=36), nullable=True),
        sa.Column('recipient_name', sa.String(length=100), nullable=False),
        sa.Column('recipient_phone', sa.String(length=30), nullable=False),
        sa.Column('channel', sa.String(length=20), nullable=True),
        sa.Column('message_content', sa.Text(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('trigger_source', sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(['recipient_id'], ['students.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_reminder_logs_id'), 'reminder_logs', ['id'], unique=False)

    if 'score_records' not in existing_tables:
        op.create_table('score_records',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('student_id', sa.String(length=36), nullable=False),
        sa.Column('category', sa.String(length=50), nullable=False),
        sa.Column('points', sa.Float(), nullable=False),
        sa.Column('max_points', sa.Float(), nullable=False),
        sa.Column('month', sa.String(length=7), nullable=True),
        sa.Column('graded_by_user_id', sa.String(length=36), nullable=True),
        sa.Column('notes', sa.String(length=255), nullable=True),
        sa.Column('updated_by', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['graded_by_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('student_id', 'category', 'month', name='uq_score_records_student_category_month')
        )
        op.create_index(op.f('ix_score_records_id'), 'score_records', ['id'], unique=False)
        op.create_index(op.f('ix_score_records_month'), 'score_records', ['month'], unique=False)
        op.create_index(op.f('ix_score_records_student_id'), 'score_records', ['student_id'], unique=False)

    if 'tasks' not in existing_tables:
        op.create_table('tasks',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('task_number', sa.Integer(), nullable=True),
        sa.Column('title', sa.String(length=150), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
        sa.Column('max_score', sa.Float(), nullable=True),
        sa.Column('score_rule', sa.String(length=100), nullable=True),
        sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
        sa.Column('team_id', sa.String(length=36), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_tasks_created_by_user_id'), 'tasks', ['created_by_user_id'], unique=False)
        op.create_index(op.f('ix_tasks_deadline'), 'tasks', ['deadline'], unique=False)
        op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
        op.create_index(op.f('ix_tasks_task_number'), 'tasks', ['task_number'], unique=True)
        op.create_index(op.f('ix_tasks_team_id'), 'tasks', ['team_id'], unique=False)

    if 'whatsapp_chat_messages' not in existing_tables:
        op.create_table('whatsapp_chat_messages',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('openwa_message_id', sa.String(length=100), nullable=True),
        sa.Column('student_id', sa.String(length=36), nullable=False),
        sa.Column('assigned_hr_id', sa.String(length=36), nullable=True),
        sa.Column('sender_type', sa.String(length=20), nullable=False),
        sa.Column('sender_id', sa.String(length=36), nullable=True),
        sa.Column('sender_phone', sa.String(length=30), nullable=False),
        sa.Column('recipient_phone', sa.String(length=30), nullable=False),
        sa.Column('message_type', sa.String(length=30), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('media_url', sa.Text(), nullable=True),
        sa.Column('media_filename', sa.String(length=255), nullable=True),
        sa.Column('media_mimetype', sa.String(length=100), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('ack_status', sa.Integer(), nullable=True),
        sa.Column('reply_to_message_id', sa.String(length=100), nullable=True),
        sa.Column('is_edited', sa.Boolean(), nullable=True),
        sa.Column('reactions', sa.Text(), nullable=True),
        sa.Column('raw_payload', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['assigned_hr_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_whatsapp_chat_messages_assigned_hr_id'), 'whatsapp_chat_messages', ['assigned_hr_id'], unique=False)
        op.create_index(op.f('ix_whatsapp_chat_messages_created_at'), 'whatsapp_chat_messages', ['created_at'], unique=False)
        op.create_index(op.f('ix_whatsapp_chat_messages_id'), 'whatsapp_chat_messages', ['id'], unique=False)
        op.create_index(op.f('ix_whatsapp_chat_messages_openwa_message_id'), 'whatsapp_chat_messages', ['openwa_message_id'], unique=False)
        op.create_index(op.f('ix_whatsapp_chat_messages_student_id'), 'whatsapp_chat_messages', ['student_id'], unique=False)

    if 'attendance_records' not in existing_tables:
        op.create_table('attendance_records',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('meeting_id', sa.String(length=36), nullable=False),
        sa.Column('student_id', sa.String(length=36), nullable=False),
        sa.Column('status', sa.String(length=30), nullable=False),
        sa.Column('match_confidence', sa.Float(), nullable=True),
        sa.Column('first_join', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_leave', sa.DateTime(timezone=True), nullable=True),
        sa.Column('total_duration_minutes', sa.Float(), nullable=True),
        sa.Column('excuse_reason', sa.Text(), nullable=True),
        sa.Column('excuse_status', sa.String(length=30), nullable=True),
        sa.Column('policy_version', sa.String(length=20), nullable=True),
        sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
        sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_attendance_records_id'), 'attendance_records', ['id'], unique=False)
        op.create_index(op.f('ix_attendance_records_meeting_id'), 'attendance_records', ['meeting_id'], unique=False)
        op.create_index(op.f('ix_attendance_records_student_id'), 'attendance_records', ['student_id'], unique=False)

    if 'meeting_assignments' not in existing_tables:
        op.create_table('meeting_assignments',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('meeting_id', sa.String(length=36), nullable=False),
        sa.Column('student_id', sa.String(length=36), nullable=False),
        sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
        sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('meeting_id', 'student_id', name='uq_meeting_student_assignment')
        )
        op.create_index(op.f('ix_meeting_assignments_id'), 'meeting_assignments', ['id'], unique=False)
        op.create_index(op.f('ix_meeting_assignments_meeting_id'), 'meeting_assignments', ['meeting_id'], unique=False)
        op.create_index(op.f('ix_meeting_assignments_student_id'), 'meeting_assignments', ['student_id'], unique=False)

    if 'participant_sessions' not in existing_tables:
        op.create_table('participant_sessions',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('meeting_id', sa.String(length=36), nullable=False),
        sa.Column('raw_display_name', sa.String(length=100), nullable=False),
        sa.Column('raw_email', sa.String(length=100), nullable=True),
        sa.Column('join_time', sa.DateTime(timezone=True), nullable=False),
        sa.Column('leave_time', sa.DateTime(timezone=True), nullable=False),
        sa.Column('duration_seconds', sa.Integer(), nullable=True),
        sa.Column('matched_student_id', sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(['matched_student_id'], ['students.id'], ),
        sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_participant_sessions_id'), 'participant_sessions', ['id'], unique=False)
        op.create_index(op.f('ix_participant_sessions_meeting_id'), 'participant_sessions', ['meeting_id'], unique=False)

    if 'submissions' not in existing_tables:
        op.create_table('submissions',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('task_id', sa.String(length=36), nullable=False),
        sa.Column('student_id', sa.String(length=36), nullable=False),
        sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('score', sa.Float(), nullable=True),
        sa.Column('technical_score', sa.Float(), nullable=True),
        sa.Column('file_url', sa.String(length=255), nullable=True),
        sa.Column('reviewer_notes', sa.Text(), nullable=True),
        sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('graded_by_user_id', sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(['graded_by_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
        sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_submissions_id'), 'submissions', ['id'], unique=False)
        op.create_index(op.f('ix_submissions_student_id'), 'submissions', ['student_id'], unique=False)
        op.create_index(op.f('ix_submissions_task_id'), 'submissions', ['task_id'], unique=False)

    if 'task_assignments' not in existing_tables:
        op.create_table('task_assignments',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('task_id', sa.String(length=36), nullable=False),
        sa.Column('student_id', sa.String(length=36), nullable=False),
        sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
        sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('task_id', 'student_id', name='uq_task_student_assignment')
        )
        op.create_index(op.f('ix_task_assignments_id'), 'task_assignments', ['id'], unique=False)
        op.create_index(op.f('ix_task_assignments_student_id'), 'task_assignments', ['student_id'], unique=False)
        op.create_index(op.f('ix_task_assignments_task_id'), 'task_assignments', ['task_id'], unique=False)

    if 'task_reminders' not in existing_tables:
        op.create_table('task_reminders',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('task_id', sa.String(length=36), nullable=False),
        sa.Column('student_id', sa.String(length=36), nullable=False),
        sa.Column('channel', sa.String(length=20), nullable=True),
        sa.Column('stage', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('message_text', sa.Text(), nullable=False),
        sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
        sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_task_reminders_id'), 'task_reminders', ['id'], unique=False)
        op.create_index(op.f('ix_task_reminders_student_id'), 'task_reminders', ['student_id'], unique=False)
        op.create_index(op.f('ix_task_reminders_task_id'), 'task_reminders', ['task_id'], unique=False)

    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())

    if 'task_reminders' in existing_tables:
        # ### commands auto generated by Alembic - please adjust! ###
        op.drop_index(op.f('ix_task_reminders_task_id'), table_name='task_reminders')
        op.drop_index(op.f('ix_task_reminders_student_id'), table_name='task_reminders')
        op.drop_index(op.f('ix_task_reminders_id'), table_name='task_reminders')
        op.drop_table('task_reminders')

    if 'task_assignments' in existing_tables:
        op.drop_index(op.f('ix_task_assignments_task_id'), table_name='task_assignments')
        op.drop_index(op.f('ix_task_assignments_student_id'), table_name='task_assignments')
        op.drop_index(op.f('ix_task_assignments_id'), table_name='task_assignments')
        op.drop_table('task_assignments')

    if 'submissions' in existing_tables:
        op.drop_index(op.f('ix_submissions_task_id'), table_name='submissions')
        op.drop_index(op.f('ix_submissions_student_id'), table_name='submissions')
        op.drop_index(op.f('ix_submissions_id'), table_name='submissions')
        op.drop_table('submissions')

    if 'participant_sessions' in existing_tables:
        op.drop_index(op.f('ix_participant_sessions_meeting_id'), table_name='participant_sessions')
        op.drop_index(op.f('ix_participant_sessions_id'), table_name='participant_sessions')
        op.drop_table('participant_sessions')

    if 'meeting_assignments' in existing_tables:
        op.drop_index(op.f('ix_meeting_assignments_student_id'), table_name='meeting_assignments')
        op.drop_index(op.f('ix_meeting_assignments_meeting_id'), table_name='meeting_assignments')
        op.drop_index(op.f('ix_meeting_assignments_id'), table_name='meeting_assignments')
        op.drop_table('meeting_assignments')

    if 'attendance_records' in existing_tables:
        op.drop_index(op.f('ix_attendance_records_student_id'), table_name='attendance_records')
        op.drop_index(op.f('ix_attendance_records_meeting_id'), table_name='attendance_records')
        op.drop_index(op.f('ix_attendance_records_id'), table_name='attendance_records')
        op.drop_table('attendance_records')

    if 'whatsapp_chat_messages' in existing_tables:
        op.drop_index(op.f('ix_whatsapp_chat_messages_student_id'), table_name='whatsapp_chat_messages')
        op.drop_index(op.f('ix_whatsapp_chat_messages_openwa_message_id'), table_name='whatsapp_chat_messages')
        op.drop_index(op.f('ix_whatsapp_chat_messages_id'), table_name='whatsapp_chat_messages')
        op.drop_index(op.f('ix_whatsapp_chat_messages_created_at'), table_name='whatsapp_chat_messages')
        op.drop_index(op.f('ix_whatsapp_chat_messages_assigned_hr_id'), table_name='whatsapp_chat_messages')
        op.drop_table('whatsapp_chat_messages')

    if 'tasks' in existing_tables:
        op.drop_index(op.f('ix_tasks_team_id'), table_name='tasks')
        op.drop_index(op.f('ix_tasks_task_number'), table_name='tasks')
        op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
        op.drop_index(op.f('ix_tasks_deadline'), table_name='tasks')
        op.drop_index(op.f('ix_tasks_created_by_user_id'), table_name='tasks')
        op.drop_table('tasks')

    if 'score_records' in existing_tables:
        op.drop_index(op.f('ix_score_records_student_id'), table_name='score_records')
        op.drop_index(op.f('ix_score_records_month'), table_name='score_records')
        op.drop_index(op.f('ix_score_records_id'), table_name='score_records')
        op.drop_table('score_records')

    if 'reminder_logs' in existing_tables:
        op.drop_index(op.f('ix_reminder_logs_id'), table_name='reminder_logs')
        op.drop_table('reminder_logs')

    if 'member_questions' in existing_tables:
        op.drop_index(op.f('ix_member_questions_team_id'), table_name='member_questions')
        op.drop_index(op.f('ix_member_questions_student_id'), table_name='member_questions')
        op.drop_index(op.f('ix_member_questions_id'), table_name='member_questions')
        op.drop_table('member_questions')

    if 'member_followup_statuses' in existing_tables:
        op.drop_index(op.f('ix_member_followup_statuses_student_id'), table_name='member_followup_statuses')
        op.drop_index(op.f('ix_member_followup_statuses_id'), table_name='member_followup_statuses')
        op.drop_index(op.f('ix_member_followup_statuses_hr_member_id'), table_name='member_followup_statuses')
        op.drop_table('member_followup_statuses')

    if 'member_feedbacks' in existing_tables:
        op.drop_index(op.f('ix_member_feedbacks_student_id'), table_name='member_feedbacks')
        op.drop_index(op.f('ix_member_feedbacks_id'), table_name='member_feedbacks')
        op.drop_index(op.f('ix_member_feedbacks_hr_member_id'), table_name='member_feedbacks')
        op.drop_table('member_feedbacks')

    if 'meetings' in existing_tables:
        op.drop_index(op.f('ix_meetings_team_id'), table_name='meetings')
        op.drop_index(op.f('ix_meetings_responsible_user_id'), table_name='meetings')
        op.drop_index(op.f('ix_meetings_meeting_code'), table_name='meetings')
        op.drop_index(op.f('ix_meetings_id'), table_name='meetings')
        op.drop_table('meetings')

    if 'committee_reports' in existing_tables:
        op.drop_index(op.f('ix_committee_reports_team_id'), table_name='committee_reports')
        op.drop_index(op.f('ix_committee_reports_submitted_by_user_id'), table_name='committee_reports')
        op.drop_index(op.f('ix_committee_reports_id'), table_name='committee_reports')
        op.drop_table('committee_reports')

    if 'automation_settings' in existing_tables:
        op.drop_index(op.f('ix_automation_settings_user_id'), table_name='automation_settings')
        op.drop_index(op.f('ix_automation_settings_id'), table_name='automation_settings')
        op.drop_table('automation_settings')

    if 'users' in existing_tables:
        op.drop_index(op.f('ix_users_team_id'), table_name='users')
        op.drop_index(op.f('ix_users_student_id'), table_name='users')
        op.drop_index(op.f('ix_users_id'), table_name='users')
        op.drop_index(op.f('ix_users_email'), table_name='users')
        op.drop_table('users')

    if 'teams' in existing_tables:
        op.drop_index(op.f('ix_teams_id'), table_name='teams')
        op.drop_index(op.f('ix_teams_code'), table_name='teams')
        op.drop_table('teams')

    if 'students' in existing_tables:
        op.drop_index(op.f('ix_students_team_id'), table_name='students')
        op.drop_index(op.f('ix_students_student_code'), table_name='students')
        op.drop_index(op.f('ix_students_id'), table_name='students')
        op.drop_index(op.f('ix_students_email'), table_name='students')
        op.drop_index(op.f('ix_students_assigned_hr_id'), table_name='students')
        op.drop_index(op.f('ix_students_arabic_name'), table_name='students')
        op.drop_table('students')

    if 'events' in existing_tables:
        op.drop_index(op.f('ix_events_start_time'), table_name='events')
        op.drop_index(op.f('ix_events_id'), table_name='events')
        op.drop_table('events')

    if 'agent_action_audits' in existing_tables:
        op.drop_index(op.f('ix_agent_action_audits_tool_name'), table_name='agent_action_audits')
        op.drop_index(op.f('ix_agent_action_audits_id'), table_name='agent_action_audits')
        op.drop_index(op.f('ix_agent_action_audits_action_id'), table_name='agent_action_audits')
        op.drop_table('agent_action_audits')

    # ### end Alembic commands ###
